project:
  name: "buildfab"
  modules: ["buildfab"]
  bin: "bin"

actions:
  - name: version-check
    run: scripts/version check

  - name: version-greatest
    run: scripts/version check-greatest

  - name: version-module
    run: |
      for module in $(scripts/version modules); do
        echo "Checking module: bin/$module"
        module_version=$(bin/$module -V 2>/dev/null || echo "")
        if [ -z "$module_version" ]; then
          echo "Could not get version from bin/$module -V"
          exit 1
        fi
        # Strip 'v' prefix from module version for comparison
        module_version_clean=$(echo "$module_version" | sed 's/^v//')
        # Get expected version directly from scripts/version
        expected_version=$(scripts/version version)
        if [ "$module_version_clean" != "$expected_version" ]; then
          echo "Version mismatch: bin/$module reports $module_version, expected $expected_version"
          echo "To check manually run: bin/$module -V"
          exit 1
        fi
        echo "✓ bin/$module version matches: $module_version"
      done

  - name: run-tests
    run: go test ./... -v -race

  - name: git-untracked
    uses: git@untracked

  - name: git-uncommitted
    uses: git@uncommitted

  - name: git-modified
    uses: git@modified

  - name: build-conan
    run: ./buildtools/build-conan.sh build

  - name: build-conan-all
    run: ./buildtools/build-conan.sh build-all

  - name: package-dry-run
    run: |
      ./buildtools/build-and-package.sh clean
      ./buildtools/build-and-package.sh dry-run

  - name: package-release
    run: |
      ./buildtools/build-and-package.sh clean
      ./buildtools/build-and-package.sh release

stages:
  pre-push:
    steps:
      - action: version-check
      - action: version-greatest

      # Always run version module validation
      - action: version-module
      
      # Run tests after version module validation
      - action: run-tests
        require: [version-module]
      
      # Run Git checks for all versions      
      - action: git-untracked
      - action: git-uncommitted
      - action: git-modified
        onerror: warn

  build:
    steps:
      - action: build-conan
      - action: run-tests
        require: [build-conan]
      - action: package-dry-run
        require: [run-tests]

  release:
    steps:
      - action: build-conan
      - action: run-tests
        require: [build-conan]
      - action: build-conan-all
        require: [run-tests]
      - action: package-release
        require: [build-conan-all]
        